class SurahOption {
  const SurahOption({
    required this.number,
    required this.name,
    required this.ayatCount,
  });

  final int number;
  final String name;
  final int ayatCount;

  String get label => '$number. $name';
}

const kQuranSurahOptions = <SurahOption>[
  SurahOption(number: 1, name: 'Al-Fatihah', ayatCount: 7),
  SurahOption(number: 2, name: 'Al-Baqarah', ayatCount: 286),
  SurahOption(number: 3, name: "Ali 'Imran", ayatCount: 200),
  SurahOption(number: 4, name: "An-Nisa'", ayatCount: 176),
  SurahOption(number: 5, name: "Al-Ma'idah", ayatCount: 120),
  SurahOption(number: 6, name: "Al-An'am", ayatCount: 165),
  SurahOption(number: 7, name: "Al-A'raf", ayatCount: 206),
  SurahOption(number: 8, name: 'Al-Anfal', ayatCount: 75),
  SurahOption(number: 9, name: 'At-Taubah', ayatCount: 129),
  SurahOption(number: 10, name: 'Yunus', ayatCount: 109),
  SurahOption(number: 11, name: 'Hud', ayatCount: 123),
  SurahOption(number: 12, name: 'Yusuf', ayatCount: 111),
  SurahOption(number: 13, name: "Ar-Ra'd", ayatCount: 43),
  SurahOption(number: 14, name: 'Ibrahim', ayatCount: 52),
  SurahOption(number: 15, name: 'Al-Hijr', ayatCount: 99),
  SurahOption(number: 16, name: 'An-Nahl', ayatCount: 128),
  SurahOption(number: 17, name: 'Al-Isra', ayatCount: 111),
  SurahOption(number: 18, name: 'Al-Kahf', ayatCount: 110),
  SurahOption(number: 19, name: 'Maryam', ayatCount: 98),
  SurahOption(number: 20, name: 'Taha', ayatCount: 135),
  SurahOption(number: 21, name: 'Al-Anbiya', ayatCount: 112),
  SurahOption(number: 22, name: 'Al-Hajj', ayatCount: 78),
  SurahOption(number: 23, name: "Al-Mu'minun", ayatCount: 118),
  SurahOption(number: 24, name: 'An-Nur', ayatCount: 64),
  SurahOption(number: 25, name: 'Al-Furqan', ayatCount: 77),
  SurahOption(number: 26, name: "Asy-Syu'ara", ayatCount: 227),
  SurahOption(number: 27, name: 'An-Naml', ayatCount: 93),
  SurahOption(number: 28, name: 'Al-Qasas', ayatCount: 88),
  SurahOption(number: 29, name: "Al-'Ankabut", ayatCount: 69),
  SurahOption(number: 30, name: 'Ar-Rum', ayatCount: 60),
  SurahOption(number: 31, name: 'Luqman', ayatCount: 34),
  SurahOption(number: 32, name: 'As-Sajdah', ayatCount: 30),
  SurahOption(number: 33, name: 'Al-Ahzab', ayatCount: 73),
  SurahOption(number: 34, name: 'Saba', ayatCount: 54),
  SurahOption(number: 35, name: 'Fatir', ayatCount: 45),
  SurahOption(number: 36, name: 'Yasin', ayatCount: 83),
  SurahOption(number: 37, name: 'As-Saffat', ayatCount: 182),
  SurahOption(number: 38, name: 'Sad', ayatCount: 88),
  SurahOption(number: 39, name: 'Az-Zumar', ayatCount: 75),
  SurahOption(number: 40, name: 'Ghafir', ayatCount: 85),
  SurahOption(number: 41, name: 'Fussilat', ayatCount: 54),
  SurahOption(number: 42, name: 'Asy-Syura', ayatCount: 53),
  SurahOption(number: 43, name: 'Az-Zukhruf', ayatCount: 89),
  SurahOption(number: 44, name: 'Ad-Dukhan', ayatCount: 59),
  SurahOption(number: 45, name: 'Al-Jasiyah', ayatCount: 37),
  SurahOption(number: 46, name: 'Al-Ahqaf', ayatCount: 35),
  SurahOption(number: 47, name: 'Muhammad', ayatCount: 38),
  SurahOption(number: 48, name: 'Al-Fath', ayatCount: 29),
  SurahOption(number: 49, name: 'Al-Hujurat', ayatCount: 18),
  SurahOption(number: 50, name: 'Qaf', ayatCount: 45),
  SurahOption(number: 51, name: 'Az-Zariyat', ayatCount: 60),
  SurahOption(number: 52, name: 'At-Tur', ayatCount: 49),
  SurahOption(number: 53, name: 'An-Najm', ayatCount: 62),
  SurahOption(number: 54, name: 'Al-Qamar', ayatCount: 55),
  SurahOption(number: 55, name: 'Ar-Rahman', ayatCount: 78),
  SurahOption(number: 56, name: "Al-Waqi'ah", ayatCount: 96),
  SurahOption(number: 57, name: 'Al-Hadid', ayatCount: 29),
  SurahOption(number: 58, name: 'Al-Mujadilah', ayatCount: 22),
  SurahOption(number: 59, name: 'Al-Hasyr', ayatCount: 24),
  SurahOption(number: 60, name: 'Al-Mumtahanah', ayatCount: 13),
  SurahOption(number: 61, name: 'As-Saff', ayatCount: 14),
  SurahOption(number: 62, name: "Al-Jumu'ah", ayatCount: 11),
  SurahOption(number: 63, name: 'Al-Munafiqun', ayatCount: 11),
  SurahOption(number: 64, name: 'At-Tagabun', ayatCount: 18),
  SurahOption(number: 65, name: 'At-Talaq', ayatCount: 12),
  SurahOption(number: 66, name: 'At-Tahrim', ayatCount: 12),
  SurahOption(number: 67, name: 'Al-Mulk', ayatCount: 30),
  SurahOption(number: 68, name: 'Al-Qalam', ayatCount: 52),
  SurahOption(number: 69, name: 'Al-Haqqah', ayatCount: 52),
  SurahOption(number: 70, name: "Al-Ma'arij", ayatCount: 44),
  SurahOption(number: 71, name: 'Nuh', ayatCount: 28),
  SurahOption(number: 72, name: 'Al-Jinn', ayatCount: 28),
  SurahOption(number: 73, name: 'Al-Muzzammil', ayatCount: 20),
  SurahOption(number: 74, name: 'Al-Muddassir', ayatCount: 56),
  SurahOption(number: 75, name: 'Al-Qiyamah', ayatCount: 40),
  SurahOption(number: 76, name: 'Al-Insan', ayatCount: 31),
  SurahOption(number: 77, name: 'Al-Mursalat', ayatCount: 50),
  SurahOption(number: 78, name: 'An-Naba', ayatCount: 40),
  SurahOption(number: 79, name: "An-Nazi'at", ayatCount: 46),
  SurahOption(number: 80, name: 'Abasa', ayatCount: 42),
  SurahOption(number: 81, name: 'At-Takwir', ayatCount: 29),
  SurahOption(number: 82, name: 'Al-Infitar', ayatCount: 19),
  SurahOption(number: 83, name: 'Al-Mutaffifin', ayatCount: 36),
  SurahOption(number: 84, name: 'Al-Insyiqaq', ayatCount: 25),
  SurahOption(number: 85, name: 'Al-Buruj', ayatCount: 22),
  SurahOption(number: 86, name: 'At-Tariq', ayatCount: 17),
  SurahOption(number: 87, name: "Al-A'la", ayatCount: 19),
  SurahOption(number: 88, name: 'Al-Gasyiyah', ayatCount: 26),
  SurahOption(number: 89, name: 'Al-Fajr', ayatCount: 30),
  SurahOption(number: 90, name: 'Al-Balad', ayatCount: 20),
  SurahOption(number: 91, name: 'Asy-Syams', ayatCount: 15),
  SurahOption(number: 92, name: 'Al-Lail', ayatCount: 21),
  SurahOption(number: 93, name: 'Ad-Duha', ayatCount: 11),
  SurahOption(number: 94, name: 'Asy-Syarh', ayatCount: 8),
  SurahOption(number: 95, name: 'At-Tin', ayatCount: 8),
  SurahOption(number: 96, name: "Al-'Alaq", ayatCount: 19),
  SurahOption(number: 97, name: 'Al-Qadr', ayatCount: 5),
  SurahOption(number: 98, name: 'Al-Bayyinah', ayatCount: 8),
  SurahOption(number: 99, name: 'Az-Zalzalah', ayatCount: 8),
  SurahOption(number: 100, name: "Al-'Adiyat", ayatCount: 11),
  SurahOption(number: 101, name: "Al-Qari'ah", ayatCount: 11),
  SurahOption(number: 102, name: 'At-Takathur', ayatCount: 8),
  SurahOption(number: 103, name: "Al-'Asr", ayatCount: 3),
  SurahOption(number: 104, name: 'Al-Humazah', ayatCount: 9),
  SurahOption(number: 105, name: 'Al-Fil', ayatCount: 5),
  SurahOption(number: 106, name: 'Quraish', ayatCount: 4),
  SurahOption(number: 107, name: "Al-Ma'un", ayatCount: 7),
  SurahOption(number: 108, name: 'Al-Kawthar', ayatCount: 3),
  SurahOption(number: 109, name: 'Al-Kafirun', ayatCount: 6),
  SurahOption(number: 110, name: 'An-Nasr', ayatCount: 3),
  SurahOption(number: 111, name: 'Al-Masad', ayatCount: 5),
  SurahOption(number: 112, name: 'Al-Ikhlas', ayatCount: 4),
  SurahOption(number: 113, name: 'Al-Falaq', ayatCount: 5),
  SurahOption(number: 114, name: 'An-Nas', ayatCount: 6),
];

const kRecitationBookOptions = <String>[
  'Iqra',
  'Yanbua 1',
  'Yanbua 2',
  'Yanbua 3',
  'Yanbua 4',
  'Yanbua 5',
  'Yanbua 6',
];
