"""empty message

Revision ID: 12a1e9060913
Revises: 3516e071ac1b
Create Date: 2026-02-10 22:45:44.672699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a1e9060913'
down_revision = '3516e071ac1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('personal_job', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_candidates', schema=None) as batch_op:
        batch_op.drop_column('personal_job')
        batch_op.drop_column('personal_phone')

    # ### end Alembic commands ###
