"""initial migration - fresh database

Revision ID: 3516e071ac1b
Revises: 
Create Date: 2026-02-10 18:31:20.105076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3516e071ac1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('majlis_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.String(length=20), nullable=True),
    sa.Column('program_type', sa.Enum('RQDF_SORE', 'SEKOLAH_FULLDAY', 'MAJLIS_TALIM', name='programtype'), nullable=True),
    sa.Column('education_level', sa.Enum('NON_FORMAL', 'SD', 'SMP', 'SMA', name='educationlevel'), nullable=True),
    sa.Column('scholarship_category', sa.Enum('NON_BEASISWA', 'TAHFIDZ_5_JUZ', 'TAHFIDZ_10_30_JUZ', 'YATIM_DHUAFA', name='scholarshipcategory'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INTERVIEW', 'ACCEPTED', 'REJECTED', name='registrationstatus'), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('kk_number', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('L', 'P', name='gender'), nullable=True),
    sa.Column('place_of_birth', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('previous_school', sa.String(length=100), nullable=True),
    sa.Column('previous_school_class', sa.String(length=20), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_job', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('mother_job', sa.String(length=100), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('father_income_range', sa.String(length=50), nullable=True),
    sa.Column('mother_income_range', sa.String(length=50), nullable=True),
    sa.Column('tahfidz_schedule', sa.Enum('SHIFT_1', 'SHIFT_2', 'TIDAK_ADA', name='tahfidzschedule'), nullable=True),
    sa.Column('uniform_size', sa.Enum('S', 'M', 'L', 'XL', 'XXL', 'TIDAK_MEMILIH', name='uniformsize'), nullable=True),
    sa.Column('initial_pledge_amount', sa.Float(), nullable=True),
    sa.Column('finance_option', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_no')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('kkm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'GURU', 'SISWA', 'WALI_MURID', 'TU', 'MAJLIS_PARTICIPANT', name='userrole'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('grade_type', sa.Enum('TUGAS', 'UH', 'UTS', 'UAS', 'SIKAP', name='gradetype'), nullable=True),
    sa.Column('weight_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_contact', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('admission_fee_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_type', sa.Enum('RQDF_SORE', 'SEKOLAH_FULLDAY', 'MAJLIS_TALIM', name='programtype'), nullable=False),
    sa.Column('scholarship_category', sa.Enum('NON_BEASISWA', 'TAHFIDZ_5_JUZ', 'TAHFIDZ_10_30_JUZ', 'YATIM_DHUAFA', name='scholarshipcategory'), nullable=True),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('custom_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.Column('class_type', sa.Enum('REGULAR', 'MAJLIS_TALIM', name='classtype'), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracurriculars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('supervisor_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('learning_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('target_class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['target_class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('majlis_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.Column('majlis_class_id', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('majlis_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_majlis_participants_phone'), ['phone'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('job', sa.String(length=100), nullable=True),
    sa.Column('is_majlis_participant', sa.Boolean(), nullable=True),
    sa.Column('majlis_class_id', sa.Integer(), nullable=True),
    sa.Column('majlis_join_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_phone'), ['phone'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('majlis_subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['majlis_subject_id'], ['majlis_subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('current_class_id', sa.Integer(), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('L', 'P', name='gender'), nullable=True),
    sa.Column('place_of_birth', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('custom_spp_fee', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['current_class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('idx_student_class_academic', ['current_class_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_nis'), ['nis'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_nisn'), ['nisn'], unique=True)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('majlis_participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('STUDENT', 'PARENT_MAJLIS', 'EXTERNAL_MAJLIS', name='participanttype'), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HADIR', 'SAKIT', 'IZIN', 'ALPA', name='attendancestatus'), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['majlis_participant_id'], ['majlis_participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_date_class', ['date', 'class_id'], unique=False)
        batch_op.create_index('idx_attendance_participant_date', ['participant_type', 'date'], unique=False)

    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('TUGAS', 'UH', 'UTS', 'UAS', 'SIKAP', name='gradetype'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('fee_type_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'PARTIAL', name='paymentstatus'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('recitation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('majlis_participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('STUDENT', 'PARENT_MAJLIS', 'EXTERNAL_MAJLIS', name='participanttype'), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('recitation_source', sa.Enum('QURAN', 'BOOK', name='recitationsource'), nullable=True),
    sa.Column('surah', sa.String(length=50), nullable=True),
    sa.Column('ayat_start', sa.Integer(), nullable=True),
    sa.Column('ayat_end', sa.Integer(), nullable=True),
    sa.Column('book_name', sa.String(length=100), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('tajwid_errors', sa.Integer(), nullable=True),
    sa.Column('makhraj_errors', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_participant_id'], ['majlis_participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_score', sa.Float(), nullable=True),
    sa.Column('knowledge_predikat', sa.String(length=2), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('skill_predikat', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('spiritual_predikat', sa.String(length=20), nullable=True),
    sa.Column('spiritual_desc', sa.Text(), nullable=True),
    sa.Column('social_predikat', sa.String(length=20), nullable=True),
    sa.Column('social_desc', sa.Text(), nullable=True),
    sa.Column('sick_count', sa.Integer(), nullable=True),
    sa.Column('permit_count', sa.Integer(), nullable=True),
    sa.Column('alpha_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_extracurriculars',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('extracurricular_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extracurricular_id'], ['extracurriculars.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'extracurricular_id')
    )
    op.create_table('tahfidz_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('majlis_participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('STUDENT', 'PARENT_MAJLIS', 'EXTERNAL_MAJLIS', name='participanttype'), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('period_type', sa.Enum('BULANAN', 'TENGAH_SEMESTER', 'SEMESTER', name='evaluationperiod'), nullable=True),
    sa.Column('period_label', sa.String(length=30), nullable=True),
    sa.Column('makhraj_errors', sa.Integer(), nullable=True),
    sa.Column('tajwid_errors', sa.Integer(), nullable=True),
    sa.Column('harakat_errors', sa.Integer(), nullable=True),
    sa.Column('tahfidz_errors', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_participant_id'], ['majlis_participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahfidz_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('majlis_participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('STUDENT', 'PARENT_MAJLIS', 'EXTERNAL_MAJLIS', name='participanttype'), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('ZIYADAH', 'MURAJAAH', name='tahfidztype'), nullable=True),
    sa.Column('juz', sa.Integer(), nullable=True),
    sa.Column('surah', sa.String(length=50), nullable=True),
    sa.Column('ayat_start', sa.Integer(), nullable=True),
    sa.Column('ayat_end', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('tajwid_errors', sa.Integer(), nullable=True),
    sa.Column('makhraj_errors', sa.Integer(), nullable=True),
    sa.Column('tahfidz_errors', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_participant_id'], ['majlis_participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahfidz_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('majlis_participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.Enum('STUDENT', 'PARENT_MAJLIS', 'EXTERNAL_MAJLIS', name='participanttype'), nullable=True),
    sa.Column('total_juz', sa.Float(), nullable=True),
    sa.Column('last_surah', sa.String(length=50), nullable=True),
    sa.Column('last_ayat', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['majlis_participant_id'], ['majlis_participants.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('sanction', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['pic_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('violations')
    op.drop_table('tahfidz_summaries')
    op.drop_table('tahfidz_records')
    op.drop_table('tahfidz_evaluations')
    op.drop_table('student_extracurriculars')
    op.drop_table('student_class_history')
    op.drop_table('student_attitudes')
    op.drop_table('report_cards')
    op.drop_table('recitation_records')
    op.drop_table('invoices')
    op.drop_table('grades')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_participant_date')
        batch_op.drop_index('idx_attendance_date_class')

    op.drop_table('attendances')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_nisn'))
        batch_op.drop_index(batch_op.f('ix_students_nis'))
        batch_op.drop_index('idx_student_class_academic')

    op.drop_table('students')
    op.drop_table('schedules')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_phone'))

    op.drop_table('parents')
    with op.batch_alter_table('majlis_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_majlis_participants_phone'))

    op.drop_table('majlis_participants')
    op.drop_table('announcements')
    op.drop_table('learning_materials')
    op.drop_table('extracurriculars')
    op.drop_table('class_rooms')
    op.drop_table('admission_fee_templates')
    op.drop_table('teachers')
    op.drop_table('staff')
    op.drop_table('notification_queues')
    op.drop_table('grade_weights')
    op.drop_table('fee_types')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('student_candidates')
    op.drop_table('school_documents')
    op.drop_table('majlis_subjects')
    op.drop_table('app_configs')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
