"""Re-create tahfidz tables

Revision ID: 54493435fa3e
Revises: 3a0e3a566be1
Create Date: 2026-01-05 18:34:27.626832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54493435fa3e'
down_revision = '3a0e3a566be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tahfidz_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('ZIYADAH', 'MURAJAAH', name='tahfidztype'), nullable=True),
    sa.Column('juz', sa.Integer(), nullable=True),
    sa.Column('surah', sa.String(length=50), nullable=True),
    sa.Column('ayat_start', sa.Integer(), nullable=True),
    sa.Column('ayat_end', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahfidz_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('total_juz', sa.Float(), nullable=True),
    sa.Column('last_surah', sa.String(length=50), nullable=True),
    sa.Column('last_ayat', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tahfidz_summaries')
    op.drop_table('tahfidz_records')
    # ### end Alembic commands ###
