"""Update attendance model add class and teacher

Revision ID: 69c2281c1b1e
Revises: 54493435fa3e
Create Date: 2026-01-07 05:15:19.619167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c2281c1b1e'
down_revision = '54493435fa3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'class_rooms', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
